[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  # Disable secrets scanning for Firebase client-side config
  SECRETS_SCAN_OMIT_KEYS = "VITE_FIREBASE_API_KEY,VITE_FIREBASE_AUTH_DOMAIN,VITE_FIREBASE_PROJECT_ID,VITE_FIREBASE_STORAGE_BUCKET,VITE_FIREBASE_MESSAGING_SENDER_ID,VITE_FIREBASE_APP_ID"
  # Alternative: Disable secrets scanning entirely (uncomment if needed)
  # SECRETS_SCAN_ENABLED = false
